# ======================================================================
# @author: Guilherme Vasconcellos <guiyllw@hotmail.com>
# @version: 1.0.0
#
# @description: Compose to start LuizaLabs api
# ======================================================================
version: '3.7'

services:
  api:
    build:
      context: .
    container_name: api
    ports: 
      - 8000:8000
    environment:
      SERVER_NAME: '0.0.0.0:8000'
      MYSQL_URI: mysql+pymysql://root:root@mysql:3306/Employee
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Employee
    restart: always
